### ISSUE TITLE
Release 0.0.1 results in "no module named PixPaint-0"

### ISSUE THREAD

**Issue by saphiresouldier** [noio/PixPaint#2]
Hey, I noticed release 0.0.1 results in a "no module named PixPaint-0" error when trying to enable it after installing the .zip with Blender 3.4 (on Windows).

This is because the folder inside the PixPaint-0.0.1.zip is named "PixPaint-0.0.1", renaming the folder (inside the .zip) to "PixPaint" makes the error go away and the AddOn can be enabled in the Preferences. Hope this is helpful :)

**Comment by noio** [comment]
ahh, gotcha! So I shouldn't be using GitHub's automatic "Source Code.zip" ? I should just zip things up manually and add those to releases? Or is there another way?

**Comment by saphiresouldier** [comment]
> ahh, gotcha! So I shouldn't be using GitHub's automatic "Source Code.zip" ? I should just zip things up manually and add those to releases? Or is there another way?

I think there are several ways, zipping up releases manually being one of them. A fancy way would be to have a github action to rename the zip/folder, but from what I've seen other Blender addons on github do as an even simpler solution is to use underscores instead of dots for the release tag: so having the tag "0_0_1" instead of "0.0.1" should work (just tested it for install+enabling the addon). 

It's probably worth a bugreport with Blender too but that's another story ;)
