### ISSUE TITLE
Separate Section for Pixel Density

### ISSUE THREAD

**Issue by perludum** [noio/PixPaint#3]
Maybe it makes sense to summarize anything related to pixel density into its own box in the panel?
Namely the "Pixels Per Unit" setting and the "Rescale Selection" operator.
These are kind of in an intermediary function between texture size and UVs.

I think it might also be more clear to name the specific Unit in use in the setting: "Pixels per meter".

**Comment by noio** [comment]
Thanks! I had the *Rescale Selection* operator close to the _Pixel Density_ setting before, but I decided to group all UV modification operations together for two reasons:

1. There are also other UV operators that use the _Pixel Density_ (e.g. all the unwrapping operations)
2. I want to work towards making it even clearer which operators are "destructive" (i.e. you **can't** use them after you've already textured your model, that will jumble the texture). Some operators can preserve the texture that you've already painted on the model as they move around UV faces. The Rescale operator is obviously destructive, so it sits down there next to other destructive operators. 

I'll see if I can fetch the name of the current used unit, that sounds neat :)
